name: sgem
description: "Sistema de Gestión de Mina"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  aad_oauth: ^1.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  equatable: ^2.0.5
  excel: ^4.0.6
  file_picker: ^5.0.0
  file_saver: ^0.2.13
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.4
  get: ^4.6.6
  go_router: ^14.2.8
  html: ^0.15.0
  image: ^4.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.11.0
  multiple_result: ^5.1.0
  open_file: ^3.2.1
  package_chinalco_flutter:
    path: packages/package_chinalco_flutter
  path_provider: ^2.1.4
  pdf: ^3.5.0
  pdf_render: ^1.4.12
  pdfx: 2.6.0
  permission_handler: ^11.3.1
  printing: ^5.9.0
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  #very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/excel/Plantilla.xlsx
    - .env
